config/routes.rb
Myapp::Application.routes.draw do

  resources :precio_servicios

  resources :clientes

  resources :venta_diaria

  resources :documento_ventas

  resources :plantilla_contrato_alquilers

  resources :cuenta_bancaria

  resources :bancos

  root to: 'static#index'

  devise_for :users

  devise_scope :user do
    get 'users/new', to: 'users/registrations#new_user'
    post 'users/create_user',
        to: 'users/registrations#create_user'
    get 'user/show/:id', to: 'users/registrations#show', as: :user_show
    get 'users/index', to: 'users/registrations#index'
    get 'users/edit_user/:id', to: 'users/registrations#edit_user', as: :user_edit_user
    post 'users/update_user', to: 'users/registrations#update_user'
    delete 'users/delete_user/:id', to: 'users/registrations#delete_user', as: :user_delete_user
    get 'profile', to: 'users/profiles#profile'
    get 'profile/edit', to: 'users/profiles#edit'
    post 'profile/update', to: 'users/profiles#update'
  end

  scope module: 'users' do
    resources :mall_users
    resources :user_tiendas
  end

  resources :roles
  get 'mall_roles', to: 'roles#assign_role_mall', as: :assign_role_mall
  post 'set_mall', to: 'roles#set_mall', as: :set_mall
  post 'save_mall_roles', to: 'roles#save_mall_roles', as: :save_mall_roles

  resources :locals

  resources :malls

  resources :nivel_malls

  resources :pais

  get 'locals' => 'locals#index', as: :local_index

  get 'locals/new' => 'locals#new'

  get 'nivel_malls/index/:mall_id' => 'nivel_malls#index', as: :nivel_malls_index

  get 'nivel_malls/new/:mall_id' => 'nivel_malls#new'

  get 'actividad_economicas' => 'actividad_economicas#index', as: :actividad_economicas

  get 'actividad_economica' => 'actividad_economicas#show'

  
  resources :tipo_canon_alquilers

  resources :cambio_monedas
  post 'cambio_monedas/mf_cambio_moneda'
  
  resources :actividad_economicas

  resources :calendario_no_laborables

  resources :arrendatarios

  resources :tiendas
  post 'tiendas/mf_dynamic_filter'

  resources :contrato_alquilers


  get 'venta_diaria_bruta'                 => 'venta_diaria#index',           as: :venta_diaria_bruta
  get 'venta_diaria_bruta/:tienda_id'      => 'venta_diaria#index',           as: :venta_diaria_tienda
  get 'cobranza_alquiler'                  => 'venta_diaria#mf_cobranza',     as: :cobranza_alquiler
  get 'ventas_tiendas/:tienda_id'          => 'venta_diaria#index',           as: :ventas_tienda
  get 'ventas_tiendas/:tienda_id/:month'   => 'venta_diaria#index',           as: :ventas_tienda_mes
  get 'ventas_mall_tiendas'                => 'venta_diaria#mf_mall_tiendas', as: :ventas_mall_tiendas
  get 'ventas_mall_tiendas/:acceso/:month' => 'venta_diaria#mf_mall_tiendas'
  get 'ventas_mensuales_mall'              => 'venta_diaria#mf_mensuales',    as: :ventas_mensuales_mall
  get 'ventas_mes_tiendas'                 => 'venta_diaria#index',           as: :ventas_mes_tienda


  get 'pago_alquilers/mf_new_transferencia'       => 'pago_alquilers#mf_new_transferencia',   as: :registrar_pago_transferencia
  post '/pago_alquilers/create'                   => 'pago_alquilers#create'
  get 'pago_alquilers/mf_new_cheque_efectivo'     => 'pago_alquilers#mf_new_cheque_efectivo', as: :registrar_pago_cheque_efectivo
  post '/pago_alquilers/create_cheque'            => 'pago_alquilers#create_cheque'
  get 'pago_alquilers/:id'                        => 'pago_alquilers#show',                   as: :mostrar_recibo_pago
  get 'pagos_mensuales_mall'                      => 'pago_alquilers#mf_pagos_mensuales',     as: :pagos_mensuales_mall
  post 'pago_alquilers/facturas_tiendas'          => 'pago_alquilers#mf_facturas_tiendas'
  get 'pago_alquilers/mf_new_cheque_efectivo/:id' => 'pago_alquilers#mf_new_cheque_efectivo'
  post 'pago_alquilers/actualizar_pagos'          => 'pago_alquilers#index'
  post 'pago_alquilers/pagos'                     => 'pago_alquilers#pagos'

  resources :pago_alquilers

  scope module: 'dynamic' do
    post 'dynamic_add_actividad/actividad'
    post 'dynamic_venta_diaria/venta'
    post 'dynamic_venta_diaria/guardar_ventas'
    post 'dynamic_venta_auditoria/auditoria'
    post 'dynamic_ventas_mes/ventas'
    post 'dynamic_pago_alquilers/recibos_cobro'
    post 'dynamic_add_nivel_mall/guardar'
    post 'dynamic_filter_locals/actualizar'
    post 'dynamic_pago_alquilers/mf_facturas_tiendas'
    post 'dynamic_venta_diaria/cerrar_ventas_mes'
  end

  #CONTROLADOR DE NOTIFICACIONES MAILERS
  get 'notificar_usuarios_mall', to: 'mail_notifications#mf_notify_tiendas_mall'

  get 'notificar_tiendas_no_actualizadas', to:  'mail_notifications#mf_notify_tiendas_no_actualizadas'

  get 'envio_recibos_cobro', to:  'mail_notifications#mf_send_recibos_cobro'

  #ESTADISTICAS
  get 'estadisticas/intermensuales_ventas_alquiler', to: 'estadisticas#mf_intermensuales_vxa'
  post 'estadisticas/intermensuales', to: 'estadisticas#filtro_intermensuales'
  get 'estadisticas/mensuales_ingresos_alquiler', to: 'estadisticas#mf_mensuales_vxa'
  post 'estadisticas/mensuales', to: 'estadisticas#filtro_mensuales'
end

app/controllers/venta_diaria_controller.rb
class VentaDiariaController < ApplicationController
  before_action :set_venta_diarium, only: [:show, :edit, :update, :destroy]

  def index
    # @user_tienda = current_user.tienda
    # if @user_tienda.blank?
    #   authorize! :index, root_url, :message => "Debe tener una tienda asignada."
    # end

    @today = Time.now
    @year = @today.strftime("%Y")
    tienda_id = params[:tienda_id]

    if !(params[:month].nil?)
      @month = params[:month]
    else
      @month = @today.strftime("%m")
    end

    if tienda_id.nil?
      tienda_id = current_user.tienda
      @ventas_mall = false
    else
      @ventas_mall = true
    end

    @tienda = Tienda.find(tienda_id)

    @contrato_alquiler = ContratoAlquiler.where(tienda: @tienda)
    if @contrato_alquiler.last.tipo_canon_alquiler == 'fijo' || @contrato_alquiler.last.tipo_canon_alquiler == 'variableVB' || @contrato_alquiler.last.tipo_canon_alquiler == 'fijo_y_variable_venta_bruta'
      @render = 'venta_bruta'
    else
      @render = 'venta_neta'
    end
  end

  def mf_cobranza

  end

  def mf_mall_tiendas
    if !params[:acceso].nil?
      @acceso = params[:acceso]
      @month = params[:month]
      @today = Time.now
      @year == @today.strftime("%Y")
      @month = Date.new(@year.to_i,@month.to_i,1)
    else
      @acceso = 1
    end
  end

  def mf_mensuales
    @mall = current_user.mall
  end


  def show

  end

  def new

  end

  def edit
  end

  def create

  end

  def update

  end

  def destroy

  end

  private
    def set_venta_diarium
      @venta_diarium = current_user.tienda.venta_diarium.find_by(id: params[:id])

    end

    def venta_diarium_params
      params.require(:venta_diarium).permit(:fecha, :monto, :monto_notas_credito, :monto_bruto, :monto_bruto_usd, :monto_costo_venta, :monto_neto, :monto_neto_usd, :editable)
    end
end

app/helpers/venta_diaria_helper.rb
module VentaDiariaHelper
end

app/views/venta_diaria/_venta_bruta.html.haml
%br
  .row
    .col-md-12
      %table.table.table-striped.table-bordered.table-hover#table_ventas_diaria_bruta
        %thead
          %tr
            %th{width: '15%'} Dia
            %th Total Venta
            %th Total Notas Credito
            %th Total Venta Bruta
        %tbody#tbody_venta_bruta.tbody_ventas_diarias

app/views/venta_diaria/_venta_neta.html.haml
%br
  .row
    .col-md-12
      %table.table.table-striped.table-bordered.table-hover#table_ventas_diaria_neta
        %thead
          %tr
            %th{width: '15%'} Dia
            %th Total Venta
            %th Total Notas Credito
            %th Total Venta Bruta
            %th Total Costo Venta
            %th Total Venta Neta
        %tbody#tbody_venta_neta.tbody_ventas_diarias

app/views/venta_diaria/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Ventas Diarias de la tienda
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      -if @ventas_mall
        %li
          = link_to 'Ventas del Mall', ventas_mall_tiendas_path
      %li
        Ventas Diarias de la tienda

.div.growlUI.save
  =image_tag 'check48.png', class: 'img-circle', width: '20px'
  Venta Guardada Exitosamente

.div.growlUI.mensaje
  =image_tag 'btn-warning.png', class: 'img-circle', width: '20px'
  No hay elementos para Guardar

.div.growlUI.mensaje_cierre
  =image_tag 'check48.png', class: 'img-circle', width: '20px'
  Cierre de Ventas del Mes se ejecuto Correctamente

.div.growlUI.mensaje_ya_cerro
  =image_tag 'btn-warning.png', class: 'img-circle', width: '20px'
  Esta Tienda ya tiene el cierre de ventas para este mes

.div.growlUI.mensaje_no_puede_cerrar
  =image_tag 'btn-warning.png', class: 'img-circle', width: '20px'
  No puede cerrar las ventas de este mes porque no tiene ventas guardadas



.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-md-3
              .col-md-5
                = form_tag(@lapso_year, :html => { :class => "form-horizontal" } ) do |f|
                  = select_year(Date.today, options = { :start_year => Time.now.year, :end_year => Time.now.year - 5, :field_name => 'lapso_year'}, :class => 'actualizar_ventas')
              .col-md-5
                = form_tag(@lapso_month, :html => { :class => "form-horizontal" } ) do |f|
                  = select_month(@month.to_i || Date.today, options = { use_month_names: %w(Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre), :field_name => 'select_month', :prefix => 'venta_diaria'}, :class => 'actualizar_ventas')

            .col-md-4
              .form-group
                .col-md-4
                  = label_tag :tienda do
                    Tienda:
                .col-md-8
                  = hidden_field_tag :tienda_id, @tienda.id
                  = text_field_tag :tienda, @tienda.nombre, autofocus: true, class: 'form-control', readonly: 'readonly'
            .col-md-4
              .form-group
                .col-md-4
                  = label_tag :nro_local do
                    Nro. de Local:
                .col-md-8
                  = text_field_tag :nro_local, @tienda.local.nro_local, class: 'form-control', readonly: 'readonly'
          .row
            .col-md-4.col-sm-offset-3
              .form-group
                .col-md-4
                  = label_tag :total_ventas do
                    Total Ventas:
                .col-md-8
                  -@suma = number_with_precision(0, precision: 2, separator: ',', delimiter: '.')
                  = text_field_tag :total_ventas, @suma, autofocus: true, class: 'form-control', placeholder:'Cargando Monto...', readonly: 'readonly'
            .col-md-4
              .form-group
                .col-md-4
                  = label_tag :canon_alquiler do
                    Canon Alquiler:
                .col-md-8
                  = text_field_tag :canon_alquiler, number_with_precision(@contrato_alquiler.last.canon_fijo_ml, precision: 2, separator: ',', delimiter: '.'), autofocus: true, class: 'form-control', readonly: 'readonly'
          = render @render

          %br
          .row
            .col-md-2
              = button_tag 'Guardar', class: 'btn btn-mall btn-block', id: 'btn_save_venta'
            .col-md-2
              = button_tag 'Cancelar', class: "btn btn-warning btn-block", id: "btn_cancelar_venta", type: "button"
            .col-md-3.col-md-offset-2
              = button_tag "Subir Documentos de Soporte", class: "btn btn-danger btn-block", id: "btn_up_documento_venta", disabled:'disabled'
            .col-md-3
              = button_tag 'Cerrar el mes de ventas', class: "btn btn-danger btn-block btn_cerrar_venta", id: "btn_cerrar_mes_venta", type: "button"

app/views/venta_diaria/mf_cobranza.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Gestion de Cobranzas de Alquiler
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        Cobranzas de Alquiler

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-md-3
              .col-md-5.col-sm-3.col-xs-5
                = form_tag(@lapso_year, :html => { :class => "form-horizontal" } ) do |f|
                  = select_year(Date.today, options = { :start_year => Time.now.year, :end_year => Time.now.year - 5, :field_name => 'lapso_year'}, :class => 'actualizar_auditoria_ventas')
              .col-md-5.col-sm-3.col-xs-5
                = form_tag(@lapso_month, :html => { :class => "form-horizontal" } ) do |f|
                  = select_month(Date.today, options = { use_month_names: %w(Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre), :field_name => 'select_month', :prefix => 'venta_diaria'}, :class => 'actualizar_auditoria_ventas')
          %br
          .row
            .col-md-4.text-right.col-md-offset-4
              = button_tag 'Enviar Recibos de Cobro&Factura', class: 'btn btn-mall btn-block', id: 'btn-send-recibos'
            .col-md-4.text-left
              = link_to notificar_tiendas_no_actualizadas_path, class: 'btn btn-danger pull-right' do
                Notificar Tiendas No Actualizadas
                %i.fa.fa-envelope
          %br
          .row
            .col-md-12
              %table.table.table-striped.table-bordered.table-hover#table_auditoria_ventas
                %thead
                  %tr
                    %th.text-center{width: '8%'}
                      Tienda
                    %th.text-center{width: '5%'}
                      Actividad Economica
                    %th.text-center{width: '7%'}
                      Local
                    %th.text-center{width: '8%'}
                      Tipo Canon
                    %th.text-center{width: '15%'}
                      Canon Fijo
                    %th.text-center{width: '15%'}
                      Monto Venta
                    %th.text-center{width: '15%'}
                      Canon Variable
                    %th.text-center{width: '15%'}
                      Total Canon
                    %th.text-center{width: '5%'}
                      Actualizada
                    %th.text-center{width: '5%'}
                      Recibo Cobro & Factura
                    %th.text-center{width: '6%'}
                      Acciones
                %tbody#tbody_auditoria_ventas
                %tfoot#tfoot_auditoria_ventas
                  %tr
                    %th{colspan: 4}
                      TOTAL
                    %td.text-right
                      %span.text-center#monto_canon_fijo
                        = @suma
                    %td.text-right
                      %span.text-center#total_ventas_mes
                        = @suma
                    %td.text-right
                      %span.text-center#monto_canon_x_venta
                        = @suma
                    %td.text-right
                      %span.text-center#total_canon
                        = @suma

app/views/venta_diaria/mf_mall_tiendas.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Reporte de Ventas del Mall x Tiendas
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      -if @acceso != 1
        %li
          = link_to 'Reporte de Pagos Mensuales', pagos_mensuales_mall_path
      %li
        Reporte de Ventas del Mall x Tiendas

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-md-3
              .col-md-5.col-sm-3.col-xs-5
                = form_tag(@lapso_year, :html => {:class => "form-horizontal" } ) do |f|
                  = select_year(Date.today, options = { :start_year => Time.now.year, :end_year => Time.now.year - 5, :field_name => 'lapso_year'}, :class => 'actualizar_auditoria_ventas')
              .col-md-5.col-sm-3.col-xs-5
                = form_tag(@lapso_month, :html => { :class => "form-horizontal" } ) do |f|
                  = select_month(@month || Date.today, options = { use_month_names: %w(Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre), :field_name => 'select_month', :prefix => 'venta_diaria', selected: @month}, :class => 'actualizar_auditoria_ventas')
          %br
          .row
            .col-md-12
              %table.table.table-striped.table-bordered.table-hover#table_mall_ventas
                %thead
                  %tr
                    %th.text-center{width: '8%'}
                      Tienda
                    %th.text-center{width: '5%'}
                      Actividad Economica
                    %th.text-center{width: '7%'}
                      Local
                    %th.text-center{width: '7%'}
                      Nivel Ubicacion
                    %th.text-center{width: '8%'}
                      Tipo Canon
                    %th.text-center{width: '13%'}
                      Monto Venta
                    %th.text-center{width: '13%'}
                      Canon Fijo
                    %th.text-center{width: '13%'}
                      Canon Variable
                    %th.text-center{width: '13%'}
                      Total Canon
                    %th.text-center{width: '6%'}
                %tbody#tbody_mall_ventas
                %tfoot#tfoot_mall_ventas
                  %tr
                    %th{width: '8%', colspan: 5}
                    %th.text-right{width: '13%'}
                      %span.text-center#total_ventas_mes_bruto
                        = @suma
                    %th.text-right{width: '13%'}
                      %span.text-center#monto_canon_fijo
                        = @suma
                    %th.text-right{width: '13%'}
                      %span.text-center#monto_canon_x_venta
                        = @suma
                    %th.text-right{width: '13%'}
                      %span.text-center#total_canon
                        = @suma

app/views/venta_diaria/mf_mensuales.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Ventas Mensuales del Mall
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        Ventas Mensuales del Mall

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          %br
          .row
            .col-md-3
              = form_tag(@lapso_year, :html => { :class => "form-horizontal" } ) do |f|
                = select_year(Date.today, options = { :start_year => Time.now.year, :end_year => Time.now.year - 5, :field_name => 'lapso_year'}, :class => 'actualizar_ventas_mes')
          %br
          %br
          .row
            .col-md-12
              %table.table.table-striped.table-bordered.table-hover.dataTables-example#table_ventas_mall
                %thead
                  %tr
                    %th.text-center Mes
                    %th.text-center Monto Ventas
                    %th.text-center Canon Fijo
                    %th.text-center Canon Variable
                    %th.text-center Total Canon
                %tbody#tbody-ventas-mall
                  %tr
                    %td.text-center Enero
                    %td.text-center{rowspan: 12, colspan: 4,style: "vertical-align: middle"}
                      %span.text-center{style: "vertical-align: middle"}
                        Cargando Datos...
                  %tr
                    %td.text-center Febrero
                  %tr
                    %td.text-center Marzo
                  %tr
                    %td.text-center Abril
                  %tr
                    %td.text-center Mayo
                  %tr
                    %td.text-center Junio
                  %tr
                    %td.text-center Julio
                  %tr
                    %td.text-center Agosto
                  %tr
                    %td.text-center Septiembre
                  %tr
                    %td.text-center Octubre
                  %tr
                    %td.text-center Noviembre
                  %tr
                    %td.text-center Diciembre
                %tfoot#tfoot-ventas-mall
                  %tr
                    %td.text-center TOTAL
                    %td#suma_total
                    %td#total_canon_fijo
                    %td#total_canon_x_ventas
                    %td#total_canons



app/views/venta_diaria/new.html.haml
.col-md-4
-@suma = number_with_precision(0, precision: 2, separator: ',', delimiter: '.')
.form-group
.col-md-5
  = label_tag :total_ventas_mes do
    Total Ventas:
.col-md-7
  -@suma = number_with_precision(0, precision: 2, separator: ',', delimiter: '.')
  = text_field_tag :total_ventas_mes, @suma, autofocus: true, class: 'form-control', readonly: 'readonly'
.col-md-4
.form-group
  .col-md-5
    = label_tag :monto_canon_fijo do
      Monto Canon Fijo:
  .col-md-7
    = text_field_tag :monto_canon_fijo, @suma, autofocus: true, class: 'form-control', readonly: 'readonly'
.row
.col-md-4.col-sm-offset-3
  .form-group
    .col-md-5
      = label_tag :monto_canon_x_venta do
        Monto Canon x Venta:
    .col-md-7
      = text_field_tag :monto_canon_x_venta, @suma, autofocus: true, class: 'form-control', readonly: 'readonly'
.col-md-4
  .form-group
    .col-md-5
      = label_tag :total_canon do
        Total Canon:
    .col-md-7
      = text_field_tag :total_canon, @suma, autofocus: true, class: 'form-control', readonly: 'readonly'