config/routes.rb
Myapp::Application.routes.draw do

  resources :precio_servicios

  resources :clientes

  resources :venta_diaria

  resources :documento_ventas

  resources :plantilla_contrato_alquilers

  resources :cuenta_bancaria

  resources :bancos

  root to: 'static#index'

  devise_for :users

  devise_scope :user do
    get 'users/new', to: 'users/registrations#new_user'
    post 'users/create_user',
        to: 'users/registrations#create_user'
    get 'user/show/:id', to: 'users/registrations#show', as: :user_show
    get 'users/index', to: 'users/registrations#index'
    get 'users/edit_user/:id', to: 'users/registrations#edit_user', as: :user_edit_user
    post 'users/update_user', to: 'users/registrations#update_user'
    delete 'users/delete_user/:id', to: 'users/registrations#delete_user', as: :user_delete_user
    get 'profile', to: 'users/profiles#profile'
    get 'profile/edit', to: 'users/profiles#edit'
    post 'profile/update', to: 'users/profiles#update'
  end

  scope module: 'users' do
    resources :mall_users
    resources :user_tiendas
  end

  resources :roles
  get 'mall_roles', to: 'roles#assign_role_mall', as: :assign_role_mall
  post 'set_mall', to: 'roles#set_mall', as: :set_mall
  post 'save_mall_roles', to: 'roles#save_mall_roles', as: :save_mall_roles

  resources :locals

  resources :malls

  resources :nivel_malls

  resources :pais

  get 'locals' => 'locals#index', as: :local_index

  get 'locals/new' => 'locals#new'

  get 'nivel_malls/index/:mall_id' => 'nivel_malls#index', as: :nivel_malls_index

  get 'nivel_malls/new/:mall_id' => 'nivel_malls#new'

  get 'actividad_economicas' => 'actividad_economicas#index', as: :actividad_economicas

  get 'actividad_economica' => 'actividad_economicas#show'

  
  resources :tipo_canon_alquilers

  resources :cambio_monedas
  post 'cambio_monedas/mf_cambio_moneda'
  
  resources :actividad_economicas

  resources :calendario_no_laborables

  resources :arrendatarios

  resources :tiendas
  post 'tiendas/mf_dynamic_filter'

  resources :contrato_alquilers


  get 'venta_diaria_bruta'                 => 'venta_diaria#index',           as: :venta_diaria_bruta
  get 'venta_diaria_bruta/:tienda_id'      => 'venta_diaria#index',           as: :venta_diaria_tienda
  get 'cobranza_alquiler'                  => 'venta_diaria#mf_cobranza',     as: :cobranza_alquiler
  get 'ventas_tiendas/:tienda_id'          => 'venta_diaria#index',           as: :ventas_tienda
  get 'ventas_tiendas/:tienda_id/:month'   => 'venta_diaria#index',           as: :ventas_tienda_mes
  get 'ventas_mall_tiendas'                => 'venta_diaria#mf_mall_tiendas', as: :ventas_mall_tiendas
  get 'ventas_mall_tiendas/:acceso/:month' => 'venta_diaria#mf_mall_tiendas'
  get 'ventas_mensuales_mall'              => 'venta_diaria#mf_mensuales',    as: :ventas_mensuales_mall
  get 'ventas_mes_tiendas'                 => 'venta_diaria#index',           as: :ventas_mes_tienda


  get 'pago_alquilers/mf_new_transferencia'       => 'pago_alquilers#mf_new_transferencia',   as: :registrar_pago_transferencia
  post '/pago_alquilers/create'                   => 'pago_alquilers#create'
  get 'pago_alquilers/mf_new_cheque_efectivo'     => 'pago_alquilers#mf_new_cheque_efectivo', as: :registrar_pago_cheque_efectivo
  post '/pago_alquilers/create_cheque'            => 'pago_alquilers#create_cheque'
  get 'pago_alquilers/:id'                        => 'pago_alquilers#show',                   as: :mostrar_recibo_pago
  get 'pagos_mensuales_mall'                      => 'pago_alquilers#mf_pagos_mensuales',     as: :pagos_mensuales_mall
  post 'pago_alquilers/facturas_tiendas'          => 'pago_alquilers#mf_facturas_tiendas'
  get 'pago_alquilers/mf_new_cheque_efectivo/:id' => 'pago_alquilers#mf_new_cheque_efectivo'
  post 'pago_alquilers/actualizar_pagos'          => 'pago_alquilers#index'
  post 'pago_alquilers/pagos'                     => 'pago_alquilers#pagos'

  resources :pago_alquilers

  scope module: 'dynamic' do
    post 'dynamic_add_actividad/actividad'
    post 'dynamic_venta_diaria/venta'
    post 'dynamic_venta_diaria/guardar_ventas'
    post 'dynamic_venta_auditoria/auditoria'
    post 'dynamic_ventas_mes/ventas'
    post 'dynamic_pago_alquilers/recibos_cobro'
    post 'dynamic_add_nivel_mall/guardar'
    post 'dynamic_filter_locals/actualizar'
    post 'dynamic_pago_alquilers/mf_facturas_tiendas'
    post 'dynamic_venta_diaria/cerrar_ventas_mes'
  end

  #CONTROLADOR DE NOTIFICACIONES MAILERS
  get 'notificar_usuarios_mall', to: 'mail_notifications#mf_notify_tiendas_mall'

  get 'notificar_tiendas_no_actualizadas', to:  'mail_notifications#mf_notify_tiendas_no_actualizadas'

  get 'envio_recibos_cobro', to:  'mail_notifications#mf_send_recibos_cobro'

  #ESTADISTICAS
  get 'estadisticas/intermensuales_ventas_alquiler', to: 'estadisticas#mf_intermensuales_vxa'
  post 'estadisticas/intermensuales', to: 'estadisticas#filtro_intermensuales'
  get 'estadisticas/mensuales_ingresos_alquiler', to: 'estadisticas#mf_mensuales_vxa'
  post 'estadisticas/mensuales', to: 'estadisticas#filtro_mensuales'
end

app/models/nivel_mall.rb
# == Schema Information
#
# Table name: nivel_malls
#
#  id         :integer          not null, primary key
#  nombre     :string(255)
#  mall_id    :integer
#  created_at :datetime
#  updated_at :datetime
#


class NivelMall < ActiveRecord::Base
  belongs_to :mall
  has_many :locals
  has_many :tiendas, through: :locals

  def self.valid_nivel_malls(user)
    return NivelMall.where(mall_id: user.mall_id)
  end


end

app/controllers/nivel_malls_controller.rb
class NivelMallsController < ApplicationController
  before_action :set_nivel_mall, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  before_action :check_user_mall

  # GET /nivel_malls
  # GET /nivel_malls.json
  def index
    @mall = Mall.find(params[:mall_id])
    @nivel_malls = NivelMall.where(mall_id: params[:mall_id])
  end

  # GET /nivel_malls/1
  # GET /nivel_malls/1.json
  def show
  end

  # GET /nivel_malls/new
  def new
    @mall = Mall.find(params[:mall_id])
    @nivel_mall = NivelMall.new
  end

  # GET /nivel_malls/1/edit
  def edit
  end

  # POST /nivel_malls
  # POST /nivel_malls.json
  def create
    @nivel_mall = NivelMall.new(nivel_mall_params)

    respond_to do |format|
      if @nivel_mall.save
        format.html { redirect_to nivel_malls_index_path(nivel_mall_params[:mall_id]), notice: 'Nivel mall fue creado exitosamente.' }
        format.json { render :index, status: :created, location: @nivel_mall }
      else
        format.html { render :new }
        format.json { render json: @nivel_mall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nivel_malls/1
  # PATCH/PUT /nivel_malls/1.json
  def update
    respond_to do |format|
      if @nivel_mall.update(nivel_mall_params)
        format.html { redirect_to nivel_malls_index_path(nivel_mall_params[:mall_id]), notice: 'Nivel mall fue actualizado exitosamente.' }
        format.json { render :index, status: :ok, location: @nivel_mall }
      else
        format.html { render :edit }
        format.json { render json: @nivel_mall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nivel_malls/1
  # DELETE /nivel_malls/1.json
  def destroy
    @mall_id = @nivel_mall.mall_id
    @nivel_mall.destroy
    respond_to do |format|
      format.html { redirect_to nivel_malls_index_path(@mall_id), notice: 'Nivel mall se elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  def test_ajax
    render :layout => nil
    respond_to do |format|
      format.json { render :index, status: :ok, location: 1 }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nivel_mall
      @nivel_mall = NivelMall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nivel_mall_params
      params.require(:nivel_mall).permit(:nombre, :mall_id)
    end
end

app/views/nivel_malls/edit.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Editar Nivel:
      = @nivel_mall.mall.nombre

    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Malls Registrados', malls_path
      %li
        = link_to 'Niveles Mall Registrados', nivel_malls_index_path(@nivel_mall.mall.id)
      %li
        Editar Nivel Mall

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            Editar Nivel Mall
        .ibox-content
          = form_for(@nivel_mall, url: {action: :create}, html: {class:"form-horizontal m-t-md", id: "form_edit_nivel_mall"}) do |f|
            - if @nivel_mall.errors.any?
              #error_explanation
                %h2
                  = pluralize(@nivel_mall.errors.count, "error")
                  prohibited this local from being saved:

                %ul
                  - @nivel_mall.errors.full_messages.each do |message|
                    %li
                      = message
            .form-group
              = f.label :nombre, "Nombre: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :nombre, autofocus: true, class: 'form-control'

            = f.hidden_field :mall_id, :value => @nivel_mall.mall.id
            .form-group
              .col-sm-3.col-sm-offset-9
                = f.submit "Actualizar", class: "btn btn-warning btn-block"

app/views/nivel_malls/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Malls Registrados
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Malls Registrados', malls_path
      %li
        Niveles del Mall Registrados


.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-sm-3
              = link_to "Nuevo Nivel Mall", { controller: "nivel_malls", action: "new", mall_id: @mall }, class: "btn btn-mall btn-block"
          %br
          .row
            .col-md-12
              %table.table.table-striped.table-bordered.table-hover.dataTables-example
                %thead
                  %tr
                    %th Nombre
                    %th Acciones
                %tbody
                  - @nivel_malls.all.each do |nivel|
                    %tr
                      %td= nivel.nombre
                      %td
                        = link_to edit_nivel_mall_path(nivel) do
                          %i.fa.fa-pencil
                          Editar
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;
                        &nbsp;

                        = link_to nivel, data: { confirm: "Seguro que desea eliminar el Nivel Mall ?" }, method: :delete do
                          %i.fa.fa-trash
                          Eliminar
                          %br

app/views/nivel_malls/new.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Nuevo Nivel:
      = @mall.nombre

    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Malls Registrados', malls_path
      %li
        = link_to 'Niveles Mall Registrados', nivel_malls_index_path(@mall)
      %li
        Registro de Nivel Mall

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            Registro de Nuevo Nivel Mall
        .ibox-content
          = form_for(@nivel_mall, url: {action: :create}, html: {class:"form-horizontal m-t-md", id: "form_registro_nivel_mall"}) do |f|
            - if @nivel_mall.errors.any?
              #error_explanation
                %h2
                  = pluralize(@nivel_mall.errors.count, "error")
                  prohibited this local from being saved:

                %ul
                  - @nivel_mall.errors.full_messages.each do |message|
                    %li
                      = message
            .form-group
              = f.label :nombre, "Nombre: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :nombre, autofocus: true, class: 'form-control'

            = f.hidden_field :mall_id, :value => @mall.id
            .form-group
              .col-sm-3.col-sm-offset-9
                = f.submit "Guardar", class: "btn btn-warning btn-block"

app/views/nivel_malls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @nivel_mall.nombre %>
</p>

<%= link_to 'Edit', edit_nivel_mall_path(@nivel_mall) %> |
<%= link_to 'Back', nivel_malls_path %>