config/routes.rb
Myapp::Application.routes.draw do

  resources :precio_servicios

  resources :clientes

  resources :venta_diaria

  resources :documento_ventas

  resources :plantilla_contrato_alquilers

  resources :cuenta_bancaria

  resources :bancos

  root to: 'static#index'

  devise_for :users

  devise_scope :user do
    get 'users/new', to: 'users/registrations#new_user'
    post 'users/create_user',
        to: 'users/registrations#create_user'
    get 'user/show/:id', to: 'users/registrations#show', as: :user_show
    get 'users/index', to: 'users/registrations#index'
    get 'users/edit_user/:id', to: 'users/registrations#edit_user', as: :user_edit_user
    post 'users/update_user', to: 'users/registrations#update_user'
    delete 'users/delete_user/:id', to: 'users/registrations#delete_user', as: :user_delete_user
    get 'profile', to: 'users/profiles#profile'
    get 'profile/edit', to: 'users/profiles#edit'
    post 'profile/update', to: 'users/profiles#update'
  end

  scope module: 'users' do
    resources :mall_users
    resources :user_tiendas
  end

  resources :roles
  get 'mall_roles', to: 'roles#assign_role_mall', as: :assign_role_mall
  post 'set_mall', to: 'roles#set_mall', as: :set_mall
  post 'save_mall_roles', to: 'roles#save_mall_roles', as: :save_mall_roles

  resources :locals

  resources :malls

  resources :nivel_malls

  resources :pais

  get 'locals' => 'locals#index', as: :local_index

  get 'locals/new' => 'locals#new'

  get 'nivel_malls/index/:mall_id' => 'nivel_malls#index', as: :nivel_malls_index

  get 'nivel_malls/new/:mall_id' => 'nivel_malls#new'

  get 'actividad_economicas' => 'actividad_economicas#index', as: :actividad_economicas

  get 'actividad_economica' => 'actividad_economicas#show'

  
  resources :tipo_canon_alquilers

  resources :cambio_monedas
  post 'cambio_monedas/mf_cambio_moneda'
  
  resources :actividad_economicas

  resources :calendario_no_laborables

  resources :arrendatarios

  resources :tiendas
  post 'tiendas/mf_dynamic_filter'

  resources :contrato_alquilers


  get 'venta_diaria_bruta'                 => 'venta_diaria#index',           as: :venta_diaria_bruta
  get 'venta_diaria_bruta/:tienda_id'      => 'venta_diaria#index',           as: :venta_diaria_tienda
  get 'cobranza_alquiler'                  => 'venta_diaria#mf_cobranza',     as: :cobranza_alquiler
  get 'ventas_tiendas/:tienda_id'          => 'venta_diaria#index',           as: :ventas_tienda
  get 'ventas_tiendas/:tienda_id/:month'   => 'venta_diaria#index',           as: :ventas_tienda_mes
  get 'ventas_mall_tiendas'                => 'venta_diaria#mf_mall_tiendas', as: :ventas_mall_tiendas
  get 'ventas_mall_tiendas/:acceso/:month' => 'venta_diaria#mf_mall_tiendas'
  get 'ventas_mensuales_mall'              => 'venta_diaria#mf_mensuales',    as: :ventas_mensuales_mall
  get 'ventas_mes_tiendas'                 => 'venta_diaria#index',           as: :ventas_mes_tienda


  get 'pago_alquilers/mf_new_transferencia'       => 'pago_alquilers#mf_new_transferencia',   as: :registrar_pago_transferencia
  post '/pago_alquilers/create'                   => 'pago_alquilers#create'
  get 'pago_alquilers/mf_new_cheque_efectivo'     => 'pago_alquilers#mf_new_cheque_efectivo', as: :registrar_pago_cheque_efectivo
  post '/pago_alquilers/create_cheque'            => 'pago_alquilers#create_cheque'
  get 'pago_alquilers/:id'                        => 'pago_alquilers#show',                   as: :mostrar_recibo_pago
  get 'pagos_mensuales_mall'                      => 'pago_alquilers#mf_pagos_mensuales',     as: :pagos_mensuales_mall
  post 'pago_alquilers/facturas_tiendas'          => 'pago_alquilers#mf_facturas_tiendas'
  get 'pago_alquilers/mf_new_cheque_efectivo/:id' => 'pago_alquilers#mf_new_cheque_efectivo'
  post 'pago_alquilers/actualizar_pagos'          => 'pago_alquilers#index'
  post 'pago_alquilers/pagos'                     => 'pago_alquilers#pagos'

  resources :pago_alquilers

  scope module: 'dynamic' do
    post 'dynamic_add_actividad/actividad'
    post 'dynamic_venta_diaria/venta'
    post 'dynamic_venta_diaria/guardar_ventas'
    post 'dynamic_venta_auditoria/auditoria'
    post 'dynamic_ventas_mes/ventas'
    post 'dynamic_pago_alquilers/recibos_cobro'
    post 'dynamic_add_nivel_mall/guardar'
    post 'dynamic_filter_locals/actualizar'
    post 'dynamic_pago_alquilers/mf_facturas_tiendas'
    post 'dynamic_venta_diaria/cerrar_ventas_mes'
  end

  #CONTROLADOR DE NOTIFICACIONES MAILERS
  get 'notificar_usuarios_mall', to: 'mail_notifications#mf_notify_tiendas_mall'

  get 'notificar_tiendas_no_actualizadas', to:  'mail_notifications#mf_notify_tiendas_no_actualizadas'

  get 'envio_recibos_cobro', to:  'mail_notifications#mf_send_recibos_cobro'

  #ESTADISTICAS
  get 'estadisticas/intermensuales_ventas_alquiler', to: 'estadisticas#mf_intermensuales_vxa'
  post 'estadisticas/intermensuales', to: 'estadisticas#filtro_intermensuales'
  get 'estadisticas/mensuales_ingresos_alquiler', to: 'estadisticas#mf_mensuales_vxa'
  post 'estadisticas/mensuales', to: 'estadisticas#filtro_mensuales'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  email                  :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  unique_session_id      :string(20)
#  name                   :string(255)
#  cellphone              :string(255)
#  avatar                 :string(255)
#  mall_id                :integer
#  locked                 :boolean          default(FALSE)
#  role_id                :integer
#  created_at             :datetime
#  updated_at             :datetime
#




class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :registerable, :recoverable,
          :rememberable, :trackable, :validatable, :session_limitable

  devise :database_authenticatable,:authentication_keys => [:username]

  mount_uploader :avatar, AvatarUploader


  belongs_to :role
  belongs_to :mall

  has_one :user_tienda, dependent: :destroy
  has_one :tienda, through: :user_tienda

  validates :username, presence: {message: 'es obligatorio'},
            uniqueness: {message: 'ya en uso.'}
  validates :email, presence: {message: 'Email Obligatorio'}
  validates :name, presence: {message: 'Nombre Obligatorio'}
  validates :role_id, presence: {message: 'Rol Obligatorio'}
  validate :admin

  def admin
    if Role.find_by(id: role_id) != Role.find(1)
      if mall_id.nil?
        errors.add(:mall_id, "Debe asignar un mall al usuario")
      end
    end
  end

  def self.mall_admins
    User.joins(:role).where(roles: {role_type: Role.role_types[:administrador_cliente]})
  end

end

app/models/user_tienda.rb
# == Schema Information
#
# Table name: user_tiendas
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  tienda_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class UserTienda < ActiveRecord::Base
  belongs_to :user
  belongs_to :tienda
end

app/controllers/users/mall_users_controller.rb
class Users::MallUsersController < ApplicationController
  before_action :authenticate_user!
  authorize_resource class: :mall_user
  before_action :set_user, only: [:destroy, :show, :edit, :update]
  before_action :set_roles, only: [:new, :edit]
  before_action :check_user_mall
  @@password = ""

  def index
    @mall_users = User.joins(:role).where(mall_id: current_user.mall.id, roles: {role_type: Role.role_types[:cliente_mall]})
  end

  def new
    @mall_user ||= User.new
  end

  def create
    @mall_user = User.new(mall_user_params.merge(mall_id: current_user.mall.id))
    @@password = mall_user_params[:password]
    respond_to do |format|
      if @mall_user.save
        PasswordMailer.send_password(@mall_user, @@password).deliver
        format.html { redirect_to  mall_user_path(@mall_user), notice: 'El usuario de MallRental se ha creado exitosamente.' }
        format.json { render :show, status: :created, location: @mall_user }
      else
        set_roles
        format.html { render :new }
        format.json { render json: @mall_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @pass = @@password
    @@password = ""
  end

  def destroy
    if @user.mall.id == current_user.mall.id && (@user.role.cliente_mall?)
      if @user.destroy
        redirect_to mall_users_path, alert: 'Usuario eliminado satisfactoriamente.' and return
      end
    else
      redirect_to mall_users_path, alert: 'No Autorizado' and return
    end
  end

  def edit

  end

  def update
    if @user.mall.id == current_user.mall.id && @user.role.cliente_mall?
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to mall_user_path(@user), notice: 'El usuario mall ha sido actualizado.' }
          format.json { render :show, status: :ok, location: @user }
        else
          set_roles
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to mall_users_path, alert: 'No Autorizado' and return
    end
  end

  private
    def mall_user_params
      params.require(:user).permit(:name, :username, :email, :password, :cellphone, :role_id, :locked)
    end

    def self.permission
      'mall_user'
    end

    def set_roles
      @roles = Role.where(role_type: Role.role_types[:cliente_mall])
      if @roles.blank?
        redirect_to new_role_path, alert: 'No existen roles para Clientes Mall.' and return
      end
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def profile
    
  end

  def edit
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to profile_path, notice: 'Su perfil ha sido actualizado.' }
        format.json { render :profile, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :avatar, :name, :cellphone)
    end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :set_user, only: [:show, :update_user, :edit_user, :delete_user]
  before_action :set_roles, only: [:new_user, :edit_user]
  @@password = ""

  def new_user
    unless user_signed_in?
      redirect_to root_url and return
    end
    @user ||= User.new
    authorize! :new, User
  end

  def create_user
    if signed_in?
      @user = User.new(user_params)
      @@password = user_params[:password]
      respond_to do |format|
        if @user.save
          PasswordMailer.send_password(@user, @@password).deliver
          format.html { redirect_to  user_show_path(@user), notice: 'El usuario de MallRental se ha creado exitosamente.' }
          format.json { render :show, status: :created, location: @user }
        else
          set_roles
          format.html { render :new_user }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url and return
    end
    authorize! :create, User
  end

  def show
    @pass = @@password
    @@password = ""
    authorize! :show, User
  end

  def index
    unless user_signed_in?
      redirect_to root_url and return
    end
    authorize! :show, User
  end

  def edit_user
    unless user_signed_in?
      redirect_to root_url and return
    end

    authorize! :update, User
  end

  def update_user
    if user_signed_in?
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to user_show_path(@user), notice: 'Usuario actualizado satisfactoriamente.' }
          format.json { render :show, status: :ok, location: @user }
        else
          set_roles
          format.html { render :edit_user }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
    authorize! :update, User
  end

  def delete_user
    if user_signed_in?
      if @user.destroy
        redirect_to users_index_path, alert: 'Usuario eliminado satisfactoriamente.' and return
      end
    end
    authorize! :update, User
  end

  private
    def set_roles
      @roles = Role.where(role_type: Role.role_types[:administrador_cliente])
      if @roles.blank?
        redirect_to new_role_path, alert: 'No existen roles para Administradores Mall.' and return
      end
    end

end

app/controllers/users/user_tiendas_controller.rb
class Users::UserTiendasController < ApplicationController
  before_action :authenticate_user!
  authorize_resource class: 'UserTienda'
  before_action :set_tienda, only: [:index, :new, :create, :destroy, :show, :edit, :update]
  before_action :set_user, only: [:destroy, :show, :edit, :update]
  before_action :set_roles, only: [:new, :edit]
  @@password = ""

  def index

  end

  def new
    @tienda = current_user.mall.tiendas.find_by(id: params[:id])
    @user = @tienda.users.build
  end

  def create
    @user = @tienda.users.build(user_tienda_params.merge(mall_id: @tienda.mall.id))
    @@password = user_tienda_params[:password]
    respond_to do |format|
      if @user.save
        PasswordMailer.send_password(@user, @@password).deliver
        format.html { redirect_to  user_tiendas_path(tienda: @user.tienda.nombre, id: @user.tienda.id), notice: "#{@user.tienda.mall.nombre} - #{@user.tienda.nombre} - Usuario creado exitosamente" }
        format.json { render :show, status: :created, location: @user }
      else
        set_roles
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @pass = @@password
    @@password = ""
  end

  def destroy
    if @user.mall.id == current_user.mall.id && (@user.role.cliente_tienda?)
      if @user.destroy
        redirect_to user_tiendas_path(tienda: @tienda.nombre, id: @tienda.id), alert: "Usuario eliminado satisfactoriamente." and return
      end
    else
      redirect_to user_tiendas_path(tienda: @tienda.nombre, id: @tienda.id), alert: 'No Autorizado' and return
    end
  end

  def edit

  end

  def update
    if @user.mall.id == current_user.mall.id && @user.role.cliente_tienda?
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to user_tiendas_path(tienda: @user.tienda.nombre, id: @user.tienda.id), notice: 'El usuario mall ha sido actualizado.' }
          format.json { render :show, status: :ok, location: @user }
        else
          set_roles
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to mall_users_path, alert: 'No Autorizado' and return
    end
  end

  private

    def set_user
      @user = @tienda.users.find_by(id: ActionController::Parameters.new(us: params[:us]).permit(:us)[:us])
    end

    def user_tienda_params
      params.require(:user).permit(:name, :username, :email, :password, :cellphone, :role_id, :tienda, :locked)
    end

    def set_tienda
      @tienda = current_user.mall.tiendas.find_by(id: ActionController::Parameters.new(id: params[:id]).permit(:id)[:id])
    end

    def set_roles
      @roles = Role.cliente_tiendas
      if @roles.blank?
        redirect_to new_role_path, alert: 'No existen Roles para Clientes Tienda.' and return
      end
    end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
end

app/views/users/user_tiendas/edit.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Usuarios Tienda")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \ -
      = @user.tienda.nombre
      \-
      Editar Usuario
      %i.fa.fa-shopping-cart
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        = link_to "#{@user.tienda.nombre} Usuarios", user_tiendas_path(tienda: @user.tienda.nombre, id: @user.tienda.id)
      %li
        Editar Usuario

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            = @user.mall.nombre
            \-
            = @user.tienda.nombre
            \-
            = @user.username
          = form_for(@user, url: {action: :update, params: {id: @user.tienda.id}}, html: {class:"form-horizontal m-t-md", id: "form_edit_usuario_mall"}) do |f|
            = devise_error_messages!
            = hidden_field_tag :us, @user.id
            .form-group
              = f.label :name, 'Nombre: ', class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :name, autofocus: true, class: 'form-control'
            .form-group
              = f.label :username, "Login: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :username, class: 'form-control'
            .form-group
              = f.label :email, "Correo Electrónico: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.email_field :email, class: "form-control"
            .form-group
              = f.label :cellphone, 'Teléfonos: ', class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :cellphone, autofocus: false, class: 'form-control'
            .form-group
              = f.label :locked, 'Bloqueado:', class: 'col-sm-2 control-label'
              .col-sm-10
                = f.check_box :locked
            .form-group
              = f.label :role, "Roles: ", class: 'col-sm-2 control-label'
              .col-sm-10
                %table
                  %tbody
                  = f.collection_radio_buttons :role_id, @roles, :id, :name do |r|
                    %tr
                      %td= r.label
                      &nbsp;
                      %td= r.radio_button
            .form-group
              .col-sm-3.col-sm-offset-9
                = f.submit "Actualizar", class: "btn btn-warning btn-block"

app/views/users/user_tiendas/index.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Usuarios Tienda")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \- Usuarios
      = @tienda.nombre
      %i.fa.fa-shopping-cart
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        Usuarios
        = @tienda.nombre

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          %h2
            = @tienda.nombre
          %br
          %br
          .row
            .col-sm-3
              = link_to "Nuevo Usuario #{@tienda.nombre}", new_user_tienda_path(tienda: @tienda.nombre, id: @tienda.id), class: 'btn btn-mall'
          %br
          .row
            .col-md-12
              .table-responsive
                %table.table.table-striped.table-bordered.table-hover
                  %thead
                    %tr
                      %th Avatar
                      %th Username
                      %th Email
                      %th Nombre
                      %th Teléfono Celular
                      %th Tienda
                      %th Rol
                      %th Acciones
                  %tbody
                    - @tienda.users.each do |user|
                      %tr
                        %td.text-center= image_tag user.avatar.url || 'building-avatar.gif', class: 'img-circle', height: 50
                        %td= user.username
                        %td= user.email
                        %td= user.name
                        %td= user.cellphone
                        %td= user.tienda.nombre rescue nil
                        %td= user.role.name_type rescue nil
                        %td
                          = link_to edit_user_tienda_path(id: @tienda.id, us: user.id) do
                            %i.fa.fa-pencil
                            Editar
                          &nbsp;
                          &nbsp;
                          &nbsp;
                          = link_to user_tienda_path(id: @tienda.id, us: user), data: { confirm: "Seguro que desea eliminar al usuario #{user.username}?" }, method: :delete do
                            %i.fa.fa-trash
                            Eliminar
          %br
          %br
          .row
            .col-sm-3
              = link_to tiendas_path, class: 'btn btn-warning btn-block' do
                Volver a Tiendas

app/views/users/user_tiendas/new.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Usuarios Tienda")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \- Nuevo Usuario -
      = @tienda.nombre
      %i.fa.fa-shopping-cart
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        = link_to "#{@tienda.nombre} Usuarios", user_tiendas_path(tienda: @tienda.nombre, id: @tienda.id)
      %li
        Registro de Usuario
        = @tienda.nombre

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            = current_user.mall.nombre
            \-
            = @tienda.nombre
            \-
            Registro de Usuario
        .ibox-content
          = form_for(@user, url: {action: :create}, html: {class:"form-horizontal m-t-md", id: "form_registro_usuario_mall"}) do |f|
            = devise_error_messages!
            = render 'shared/error_messages', object: f.object, model: 'Usuario Mall'
            = hidden_field_tag :id, @tienda.id
            .form-group
              = f.label :name, 'Nombre: ', class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :name, autofocus: true, class: 'form-control'
            .form-group
              = f.label :username, "Login: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :username, autofocus: false, class: 'form-control'
            .form-group
              = f.label :password, "Contraseña: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.password_field :password, autocomplete: "off", class: 'form-control'
                %span.help-block.m-b-none
                  La contraseña debe tener un mínimo de 8 caracteres.
            .form-group
              = f.label :password_confirmation, "Confirme Contraseña: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'
            .form-group
              = f.label :email, "Correo Electrónico: ", class: 'col-sm-2 control-label'
              .col-sm-10
                = f.email_field :email, class: "form-control"
            .form-group
              = f.label :cellphone, 'Teléfonos: ', class: 'col-sm-2 control-label'
              .col-sm-10
                = f.text_field :cellphone, autofocus: false, class: 'form-control'
            .form-group
              = f.label :role, "Roles: ", class: 'col-sm-2 control-label'
              .col-sm-10
                %table
                  %tbody
                  = f.collection_radio_buttons :role_id, @roles, :id, :name do |r|
                    %tr
                      %td= r.label
                      &nbsp;
                      %td= r.radio_button
            .form-group
              .col-sm-3.col-sm-offset-9
                = f.submit "Guardar", class: "btn btn-warning btn-block"

app/views/users/user_tiendas/show.html.haml
= provide(:title, "#{@tienda.mall.nombre } - #{@tienda.nombre} - Usuarios Tienda")
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      = current_user.mall.nombre
      \-
      = @user.tienda.nombre
      \- Nuevo Usuario
      %i.fa.fa-shopping-cart
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        = link_to 'Tiendas', tiendas_path
      %li
        = link_to "#{@user.tienda.nombre}Usuarios", user_tiendas_path
      %li
        = link_to "Registro de Usuario #{@user.tienda.nombre}", new_user_tienda_path
      %li
        Nuevo Usuario

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            = current_user.mall.nombre
            \- Usuario
        .ibox-content
          %p#notice= notice
          %h4
            %strong Nombre:
            = @user.name
          %h4
            %strong Username:
            = @user.username
          %h4
            %strong Contraseña:
            = @pass
          %h4
            %strong Correo Electrónico:
            = @user.email
          %h4
            %strong Teléfonos:
            = @user.cellphone
          %h4
            %strong Mall:
            = @user.mall.nombre rescue nil
          %h4
            %strong Rol:
            = @user.role.name_type
          %br/
          .row
            .col-md-12
              .alert.alert-danger.alert-dismissable.alerts-fix
                %strong
                  NOTA: La contraseña solo podra ser visualizada unicamente al momento del registro.
          .row
            .col-sm-3
              = link_to user_tiendas_path, class: 'btn btn-warning btn-block' do
                Regresar