config/routes.rb
Myapp::Application.routes.draw do

  resources :precio_servicios

  resources :clientes

  resources :venta_diaria

  resources :documento_ventas

  resources :plantilla_contrato_alquilers

  resources :cuenta_bancaria

  resources :bancos

  root to: 'static#index'

  devise_for :users

  devise_scope :user do
    get 'users/new', to: 'users/registrations#new_user'
    post 'users/create_user',
        to: 'users/registrations#create_user'
    get 'user/show/:id', to: 'users/registrations#show', as: :user_show
    get 'users/index', to: 'users/registrations#index'
    get 'users/edit_user/:id', to: 'users/registrations#edit_user', as: :user_edit_user
    post 'users/update_user', to: 'users/registrations#update_user'
    delete 'users/delete_user/:id', to: 'users/registrations#delete_user', as: :user_delete_user
    get 'profile', to: 'users/profiles#profile'
    get 'profile/edit', to: 'users/profiles#edit'
    post 'profile/update', to: 'users/profiles#update'
  end

  scope module: 'users' do
    resources :mall_users
    resources :user_tiendas
  end

  resources :roles
  get 'mall_roles', to: 'roles#assign_role_mall', as: :assign_role_mall
  post 'set_mall', to: 'roles#set_mall', as: :set_mall
  post 'save_mall_roles', to: 'roles#save_mall_roles', as: :save_mall_roles

  resources :locals

  resources :malls

  resources :nivel_malls

  resources :pais

  get 'locals' => 'locals#index', as: :local_index

  get 'locals/new' => 'locals#new'

  get 'nivel_malls/index/:mall_id' => 'nivel_malls#index', as: :nivel_malls_index

  get 'nivel_malls/new/:mall_id' => 'nivel_malls#new'

  get 'actividad_economicas' => 'actividad_economicas#index', as: :actividad_economicas

  get 'actividad_economica' => 'actividad_economicas#show'

  
  resources :tipo_canon_alquilers

  resources :cambio_monedas
  post 'cambio_monedas/mf_cambio_moneda'
  
  resources :actividad_economicas

  resources :calendario_no_laborables

  resources :arrendatarios

  resources :tiendas
  post 'tiendas/mf_dynamic_filter'

  resources :contrato_alquilers


  get 'venta_diaria_bruta'                 => 'venta_diaria#index',           as: :venta_diaria_bruta
  get 'venta_diaria_bruta/:tienda_id'      => 'venta_diaria#index',           as: :venta_diaria_tienda
  get 'cobranza_alquiler'                  => 'venta_diaria#mf_cobranza',     as: :cobranza_alquiler
  get 'ventas_tiendas/:tienda_id'          => 'venta_diaria#index',           as: :ventas_tienda
  get 'ventas_tiendas/:tienda_id/:month'   => 'venta_diaria#index',           as: :ventas_tienda_mes
  get 'ventas_mall_tiendas'                => 'venta_diaria#mf_mall_tiendas', as: :ventas_mall_tiendas
  get 'ventas_mall_tiendas/:acceso/:month' => 'venta_diaria#mf_mall_tiendas'
  get 'ventas_mensuales_mall'              => 'venta_diaria#mf_mensuales',    as: :ventas_mensuales_mall
  get 'ventas_mes_tiendas'                 => 'venta_diaria#index',           as: :ventas_mes_tienda


  get 'pago_alquilers/mf_new_transferencia'       => 'pago_alquilers#mf_new_transferencia',   as: :registrar_pago_transferencia
  post '/pago_alquilers/create'                   => 'pago_alquilers#create'
  get 'pago_alquilers/mf_new_cheque_efectivo'     => 'pago_alquilers#mf_new_cheque_efectivo', as: :registrar_pago_cheque_efectivo
  post '/pago_alquilers/create_cheque'            => 'pago_alquilers#create_cheque'
  get 'pago_alquilers/:id'                        => 'pago_alquilers#show',                   as: :mostrar_recibo_pago
  get 'pagos_mensuales_mall'                      => 'pago_alquilers#mf_pagos_mensuales',     as: :pagos_mensuales_mall
  post 'pago_alquilers/facturas_tiendas'          => 'pago_alquilers#mf_facturas_tiendas'
  get 'pago_alquilers/mf_new_cheque_efectivo/:id' => 'pago_alquilers#mf_new_cheque_efectivo'
  post 'pago_alquilers/actualizar_pagos'          => 'pago_alquilers#index'
  post 'pago_alquilers/pagos'                     => 'pago_alquilers#pagos'

  resources :pago_alquilers

  scope module: 'dynamic' do
    post 'dynamic_add_actividad/actividad'
    post 'dynamic_venta_diaria/venta'
    post 'dynamic_venta_diaria/guardar_ventas'
    post 'dynamic_venta_auditoria/auditoria'
    post 'dynamic_ventas_mes/ventas'
    post 'dynamic_pago_alquilers/recibos_cobro'
    post 'dynamic_add_nivel_mall/guardar'
    post 'dynamic_filter_locals/actualizar'
    post 'dynamic_pago_alquilers/mf_facturas_tiendas'
    post 'dynamic_venta_diaria/cerrar_ventas_mes'
  end

  #CONTROLADOR DE NOTIFICACIONES MAILERS
  get 'notificar_usuarios_mall', to: 'mail_notifications#mf_notify_tiendas_mall'

  get 'notificar_tiendas_no_actualizadas', to:  'mail_notifications#mf_notify_tiendas_no_actualizadas'

  get 'envio_recibos_cobro', to:  'mail_notifications#mf_send_recibos_cobro'

  #ESTADISTICAS
  get 'estadisticas/intermensuales_ventas_alquiler', to: 'estadisticas#mf_intermensuales_vxa'
  post 'estadisticas/intermensuales', to: 'estadisticas#filtro_intermensuales'
  get 'estadisticas/mensuales_ingresos_alquiler', to: 'estadisticas#mf_mensuales_vxa'
  post 'estadisticas/mensuales', to: 'estadisticas#filtro_mensuales'
end

app/models/pago_alquiler.rb
# == Schema Information
#
# Table name: pago_alquilers
#
#  id                      :integer          not null, primary key
#  nro_recibo              :string(255)
#  fecha_recibo_cobro      :date
#  anio_alquiler           :integer
#  mes_alquiler            :integer
#  monto_canon_fijo_ml     :decimal(, )
#  monto_porc_ventas_ml    :decimal(, )
#  monto_alquiler_ml       :decimal(, )
#  monto_alquiler_usd      :decimal(, )
#  pagado                  :boolean
#  fecha_pago              :date
#  nro_cheque_confirmacion :string(255)
#  archivo_transferencia   :string(255)
#  nombre_banco            :string(255)
#  facturado               :boolean
#  nro_factura             :string(255)
#  fecha_factura           :date
#  tipo_pago               :integer
#  contrato_alquiler_id    :integer
#  tienda_id               :integer
#  cuenta_bancarium_id     :integer
#  created_at              :datetime
#  updated_at              :datetime
#



class PagoAlquiler < ActiveRecord::Base
  belongs_to :cuenta_bancarium
  has_many :detalle_pago_alquilers
  has_many :factura_alquilers, through: :detalle_pago_alquilers

  before_create :set_missing_attributes_create
  accepts_nested_attributes_for :detalle_pago_alquilers, allow_destroy: true

  enum tipo_pago: [:Cheque, :Transferencia, :Efectivo]

  def self.valid_forma_pago
    %w[Cheque Efectivo]
  end

  def set_missing_attributes_create
    self.nro_recibo = NroRecibo.get_numero_recibo
    self.monto_usd = self.monto / CambioMoneda.last.cambio_ml_x_usd
  end

end

app/controllers/pago_alquilers_controller.rb
class PagoAlquilersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_pago_alquiler, only: [:show, :edit, :update, :destroy]
  before_action :check_user_mall

  # GET /pago_alquilers
  # GET /pago_alquilers.json
  def index

    if params[:year].nil?
      today = Time.now
      month = today.strftime("%-m").to_i
      year = today.strftime("%Y")
    else
      month = params[:month]
      year = params[:year]
    end

    @cobranza_alquilers = CobranzaAlquiler.get_cobranza_mes_xtienda(current_user.mall,year,month)
    @suma_monto_x_cobrar = CobranzaAlquiler.saldo_deudor_x_mes(current_user.mall,year,month)
    @suma_monto_alquiler = CobranzaAlquiler.monto_alquiler_x_mes(current_user.mall,year,month)
    @suma_monto_pagado = @suma_monto_alquiler - @suma_monto_x_cobrar

    if @suma_monto_pagado > 0
      @month = month.to_i
    elsif
      if params[:month].nil?
        month -= 1
        @month = month.to_i
        @cobranza_alquilers = CobranzaAlquiler.get_cobranza_mes_xtienda(current_user.mall,year,month)
        @suma_monto_x_cobrar = CobranzaAlquiler.saldo_deudor_x_mes(current_user.mall,year,month)
        @suma_monto_alquiler = CobranzaAlquiler.monto_alquiler_x_mes(current_user.mall,year,month)
        @suma_monto_pagado = @suma_monto_alquiler - @suma_monto_x_cobrar
      else
        @month = params[:month].to_i
      end
    end
  end

  # GET /pago_alquilers/1
  # GET /pago_alquilers/1.json
  def show
  end

  # GET /pago_alquilers/new
  def mf_new_transferencia
    tienda = current_user.tienda
    if tienda.blank?
      authorize! :index, root_url, :message => "Debe tener una tienda asignada."
    end
    
    @facturas_x_pagar = CobranzaAlquiler.get_facturas_x_pagar(tienda.id)
    @total_facturado = FacturaAlquiler.get_total_facturado(tienda.id)
    @total_x_pagar = CobranzaAlquiler.saldo_deudor_x_tienda(tienda.id)
    @pago_alquiler = PagoAlquiler.new
    @detalle_pago_alquiler = @pago_alquiler.detalle_pago_alquilers.build
  end

  def mf_new_cheque_efectivo
    @pago_alquiler = PagoAlquiler.new
  end

  # GET /pago_alquilers/1/edit
  def edit
  end

  # POST /pago_alquilers
  # POST /pago_alquilers.json
  def create

    @pago_alquiler = PagoAlquiler.new(pago_alquiler_params)
    respond_to do |format|
      if @pago_alquiler.save
        cant_fact = params[:pago_alquiler][:detalle_pago_alquilers_attributes].length
        for i in (0..cant_fact-1)
          num = i.to_s
          monto = params[:pago_alquiler][:detalle_pago_alquilers_attributes][num]['monto_fact']
          factura_id = params[:pago_alquiler][:detalle_pago_alquilers_attributes][num]['factura_alquiler_id']
          cobranza_id = params[:pago_alquiler][:detalle_pago_alquilers_attributes][num]['cobranza_alquiler_id']

          pago_id = @pago_alquiler.id
          detalle =  DetallePagoAlquiler.new(monto: monto, pago_alquiler_id: pago_id, factura_alquiler_id: factura_id)
          cobranza_alquiler = CobranzaAlquiler.find(cobranza_id)

          factura = FacturaAlquiler.find(factura_id)
          monto_abonado = factura.monto_abono.to_f
          monto_abono = monto_abonado + monto.to_f
          monto_factura = factura.monto_factura
          saldo_deudor = monto_factura - monto_abono
          obj = {
              :monto_abono => monto_abono,
              :saldo_deudor => saldo_deudor,
          }
          fact_alquiler = obj

          if detalle.save
            factura.update(fact_alquiler)
            cobranza_alquiler.update(saldo_deudor: saldo_deudor)
            format.html { redirect_to pago_alquilers_path, notice: 'Pago Alquiler guardado existosamente.' }
            format.json { render :index, status: :created, location: @pago_alquiler }
          else
            format.html { render :new }
            format.json { render json: @pago_alquiler.errors, status: :unprocessable_entity }
          end
        end
      else
        format.html { render :new }
        format.json { render json: @pago_alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  def mf_facturas_tiendas

    @tienda_id = params[:tienda_id]
    @pago_alquiler = PagoAlquiler.new
    @detalle_pago_alquiler = @pago_alquiler.detalle_pago_alquilers.build

    @facturas_x_pagar = CobranzaAlquiler.get_facturas_x_pagar(@tienda_id)
    @total_x_pagar = CobranzaAlquiler.saldo_deudor_x_tienda(@tienda_id)
    @total_facturado = FacturaAlquiler.get_total_facturado(@tienda_id)

  end

  def mf_pagos_mensuales
    year = Time.now.strftime("%Y")
    mall = current_user.mall

    @cobranzas = CobranzaAlquiler.get_cobranza_xmes(mall,year)
    @totales = CobranzaAlquiler.get_total_cobranzas_xmes(mall,year)


  end

  def pagos
    year = params[:year]
    mall = current_user.mall

    @cobranzas = CobranzaAlquiler.get_cobranza_xmes(mall,year)
    @totales = CobranzaAlquiler.get_total_cobranzas_xmes(mall,year)

    render partial: 'pagos_mensuales'
  end

  # PATCH/PUT /pago_alquilers/1
  # PATCH/PUT /pago_alquilers/1.json
  def update
    respond_to do |format|
      if @pago_alquiler.update(pago_alquiler_params)
        format.html { redirect_to pago_alquilers_url, notice: 'Pago alquiler se guardo fino.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pago_alquiler.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /pago_alquilers/1
  # DELETE /pago_alquilers/1.json
  def destroy
    @pago_alquiler.destroy
    respond_to do |format|
      format.html { redirect_to pago_alquilers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pago_alquiler
      @pago_alquiler = PagoAlquiler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pago_alquiler_params
      params.require(:pago_alquiler).permit(:nro_recibo, :fecha, :monto, :monto_usd, :nro_cheque_confirmacion, :banco_emisor, :tipo_pago, :cuenta_bancarium_id, detalle_pago_alquilers_params: [:factura_alquiler_id, :monto, :pago_alquiler_id] )
    end
end

app/helpers/pago_alquilers_helper.rb
module PagoAlquilersHelper
end

app/views/pago_alquilers/_datos_recibo.html.haml
%p
  %strong Tienda:
  = @pago_alquiler.tienda.nombre
  %p
    %strong Periodo Cancelado:
    = @pago_alquiler.mes_alquiler
    = '/'
    = @pago_alquiler.anio_alquiler
  %p
    %strong Número de Recibo:
    = @pago_alquiler.nro_recibo
  %p
    %strong Monto de Pago:
    -@pago = number_with_precision(@pago_alquiler.monto_alquiler_ml, precision: 2, separator: ',', delimiter: '.')
    = @pago
  %p
    %strong Fecha de Pago:
    = @pago_alquiler.fecha_pago.strftime("%d/%m/%Y")
  %p
    %strong Forma de Pago:
    = @pago_alquiler.tipo_pago.humanize.capitalize

  - if @pago_alquiler.tipo_pago == 'Cheque'
    %p
      %strong Nro de Cheque:
      = @pago_alquiler.nro_cheque_confirmacion
    %p
      %strong Cheque del Banco:
      = @pago_alquiler.nombre_banco

  - if @pago_alquiler.tipo_pago == 'Transferencia'
    %p
      %strong Nro Transferencia:
      = @pago_alquiler.nro_cheque_confirmacion
    %p
      %strong Banco Emisor de la transferencia:
      = @pago_alquiler.nombre_banco
    %p
      %strong Cuenta Bancaria de la  Transfencia:
      = CuentaBancarium.find(@pago_alquiler.cuenta_bancaria_id).banco.nombre
  %br
  %p
    = link_to envio_recibos_cobro_path, class: 'btn btn-warning pull-left' do
      Ver Recibo de Cobro

app/views/pago_alquilers/_new_cheque_efect.html.haml
- if @facturas_array.blank?
  %tr
    %td.text-center{colspan: 7}
      - if @cantidad == 0 && !@tienda_id.nil?
        %span.text-center.vacio
          No se encontraron facturas por pagar
      - else
        %span.text-center
          Debe seleccionar una tienda para buscar las Facturas x Pagar

app/views/pago_alquilers/_pagos_mensuales.html.haml
- if @totales[:result]
  - @cobranzas.each do |cobranza|
    %tr
      %td.text-center
        = cobranza[:mes]
      %td.text-center
        = cobranza[:canon_fijo]
      %td.text-center
        = cobranza[:canon_variable]
      %td.text-center
        = cobranza[:facturado]
      %td.text-center
        = cobranza[:pagado]
      %td.text-center
        = cobranza[:pagado_usd]
      %td.text-center
        = cobranza[:x_cobrar]
      %td.text-center
        = link_to ventas_mes_tienda_path(month: cobranza[:num_mes]) do
          %i.fa.fa-search
          Ver Detalles de Pagos
  %tr#tfoot-ventas-mensuales-mall
    %td.text-center TOTAL
    %td#suma_pagado_canon_fijo
      = @totales[:total_canon_fijo]
    %td#suma_pagado_canon_variable
      = @totales[:total_canon_variable]
    %td#suma_total_facturado
      = @totales[:total_facturado]
    %td#suma_total_pagado
      = @totales[:total_pagado]
    %td#suma_total_pagado_usd
      = @totales[:total_pagado_usd]
    %td#suma_monto_x_cobrar
      = @totales[:total_x_cobrar]
- else
  %tr
    %td.text-center Enero
    %td.text-center{rowspan: 12, colspan: 7,style: "vertical-align: middle"}
      %span.text-center.texto_cargando{style: "vertical-align: middle"}
        No se encontraron Datos...
  %tr
    %td.text-center Febrero
    %tr
      %td.text-center Marzo
    %tr
      %td.text-center Abril
    %tr
      %td.text-center Mayo
    %tr
      %td.text-center Junio
    %tr
      %td.text-center Julio
    %tr
      %td.text-center Agosto
    %tr
      %td.text-center Septiembre
    %tr
      %td.text-center Octubre
    %tr
      %td.text-center Noviembre
    %tr
      %td.text-center Diciembre

app/views/pago_alquilers/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Reporte de Pagos Alquiler x Tienda
    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        Reporte de Pagos Alquiler x Tienda

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-md-4
              .col-md-5.col-sm-3.col-xs-3
                = form_tag(@lapso_year, :html => { :class => "form-horizontal" } ) do |f|
                  = select_year(Date.today, options = { :start_year => Time.now.year, :end_year => Time.now.year - 5, :field_name => 'lapso_year'}, :class => 'actualizar_pagos_alquiler')
              .col-md-5
                = form_tag(@lapso_month, :html => { :class => "form-horizontal" } ) do |f|
                  = select_month(@month || Date.today, options = { use_month_names: %w(Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre), :field_name => 'select_month', :prefix => 'pagos_alquiler'}, :class => 'actualizar_pagos_alquiler')
          %br
          .row
            .col-md-12
              %table.table.table-striped.table-bordered.table-hover#table_pagos_mall
                %thead#thead_top
                  %tr
                    %td.vacia
                    %th.text-center{colspan: 3}
                      Cobranza
                    %th.text-center{colspan: 4}
                      Pago
                %thead
                  %tr
                    %th.text-center{width: '10%'}
                      Tienda
                    %th.text-center{width: '8%'}
                      Nro Recibo
                    %th.text-center{width: '15%'}
                      Fecha Cobro
                    %th.text-center{width: '18%'}
                      Monto
                    %th.text-center{width: '6%'}
                      Cancelado
                    %th.text-center{width: '6%'}
                      Abonado
                    %th.text-center{width: '18%'}
                      Monto Pago
                    %th.text-center{width: '18%'}
                      Monto x Cobrar
                %tbody#tbody_pagos_alquiler
                  - if !@cobranza_alquilers.blank?
                    - @cobranza_alquilers.each do |cobranzas|
                      -cobranzas.each do |cobranza|
                        - if cobranza.saldo_deudor == 0
                          - @pagado = true
                          - @abonado = false
                          - monto = cobranza.monto_alquiler
                          - monto_pagado = monto
                          - monto_x_cobrar = 0
                        - else
                          - @pagado = false
                          - @abonado = true
                          - monto = cobranza.monto_alquiler
                          - monto_x_cobrar = cobranza.saldo_deudor
                          - monto_pagado = monto - monto_x_cobrar
                        %tr
                          %td= cobranza.tienda.nombre
                          %td{ :class => 'text-center' }
                            = cobranza.nro_recibo
                          %td= cobranza.fecha_recibo_cobro.strftime("%d/%m/%Y")
                          %td{ :class => 'text-right' }
                            = ActionController::Base.helpers.number_to_currency(monto, separator: ',', delimiter: '.', format: "%n %u", unit: "")
                          %td{ :class => 'text-center' }
                            = check_box_tag 'alquiler_pago', 'Pago Realizado', @pagado, disabled: true
                          %td{ :class => 'text-center' }
                            = check_box_tag 'alquiler_pago', 'Pago Realizado', @abonado, disabled: true
                          %td{ :class => 'text-right' }
                            = ActionController::Base.helpers.number_to_currency(monto_pagado, separator: ',', delimiter: '.', format: "%n %u", unit: "")
                          %td{ :class => 'text-right' }
                            = ActionController::Base.helpers.number_to_currency(monto_x_cobrar, separator: ',', delimiter: '.', format: "%n %u", unit: "")

                  - else
                    %tr
                      %td.text-center{colspan: 8}= 'No existen registros de pago para este periodo'
                %tfoot#tfoot_pagos_alquiler
                  - if !@cobranza_alquilers.blank?
                    %tr
                      %td{colspan: 2}
                      %th
                        Total:
                      %td#td_suma_monto_alquiler
                        = text_field_tag :input_suma_monto_alquiler,ActionController::Base.helpers.number_to_currency(@suma_monto_alquiler, separator: ',', delimiter: '.', format: "%n %u", unit: ""), class: 'form-control', readonly: 'readonly'
                      %td{colspan: 2}
                      %td#td_suma_monto_pagado
                        = text_field_tag :input_suma_monto_pagado, ActionController::Base.helpers.number_to_currency(@suma_monto_pagado, separator: ',', delimiter: '.', format: "%n %u", unit: ""), class: 'form-control', readonly: 'readonly'
                      %td#td_suma_monto_x_cobrar
                        = text_field_tag :input_suma_monto_x_cobrar, ActionController::Base.helpers.number_to_currency(@suma_monto_x_cobrar, separator: ',', delimiter: '.', format: "%n %u", unit: ""), class: 'form-control', readonly: 'readonly'

app/views/pago_alquilers/mf_new_cheque_efectivo.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Nuevo Pago Alquiler

    %ol.breadcrumb
      %li
        = link_to 'Inicio', root_url
      %li
        Registro de Pago Alquiler x Cheque o Efectivo

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            Registro de Pago Alquiler x Cheque o Efectivo
        .ibox-content
          = form_for(@pago_alquiler, url: {action: :create}, html: {class:"form-horizontal m-t-md", id: "form_registro_pago_cheque", :multipart => true}) do |f|
            - if @pago_alquiler.errors.any?
              #error_explanation
                %h2
                  = pluralize(@pago_alquiler.errors.count, "error")
                  prohibited this local from being saved:
                %ul
                  - @pago_alquiler.errors.full_messages.each do |message|
                    %li
                      = message
            .row
              .col-md-12
                .form-group
                  .col-md-2
                    = label_tag :tienda do
                      Tienda:
                  .col-md-3
                    = collection_select :tienda, "id", Tienda.valid_tiendas(current_user), :id, :nombre, {selected: @tienda_id, include_blank: 'Seleccione una Tienda'}, {class: 'form-control tabla_fact_tienda'}

            .row
              .col-md-12
                .col-lg-2
                  Facturas x Pagar
                .col-md-9
                  %table.table.table-striped.table-bordered.table-hover#table_facturas_pendientes
                    %thead
                      %tr
                        %th{width: '15%'} Fecha
                        %th Nro Factura
                        %th Monto Factura
                        %th Saldo Deudor
                        %th Pago Total
                        %th Abono
                        %th Monto
                    %tbody.tbody_facturas_pendientes
                      = render :partial => "new_cheque_efect"
                    %tfoot
                      %td{colspan: 2, style: "text-align: right"}
                        Por Pagar
                      %td.total_x_pagar
                        = text_field_tag :total_x_pagar, @total_x_pagar_v, class: 'form-control', readonly: 'readonly'
                      %td.total_facturado
                        = text_field_tag :@total_facturado, number_with_delimiter(@total_facturado), class: 'form-control', readonly: 'readonly'
                      %td{colspan: 2, style: "text-align: right"}
                        Total a Pagar
                      %td.total_a_pagar
                        = text_field_tag :total_a_pagar, '', class: 'form-control', readonly: 'readonly', campo: @id_fact.to_s
            .row
              .col-md-12
                .form-group
                  = label_tag :monto_campo,class: 'col-sm-2 control-label' do
                    Monto a Pagar:
                  .col-sm-10
                    = text_field_tag :monto_campo,{},class: 'form-control monto_numerico', readonly: 'readonly', id: 'monto_cheque'
                .form-group
                  = f.label :fecha, "Fecha de Pago:", class: 'col-sm-2 control-label'
                  .col-sm-10
                    #datepicker.input-daterange.input-group
                      = f.text_field :fecha,class: 'input-sm form-control',:value => "#{Date.today.strftime("%d/%m/%Y")}",  id: 'fecha_pago'
                .form-group
                  = f.label :tipo_pago, "Forma de Pago: ", class: 'col-sm-2 control-label'
                  .col-sm-10
                    = f.select(:tipo_pago, PagoAlquiler.valid_forma_pago.map { |x| [x.humanize.titleize, x]}, {selected: f.object.tipo_pago, include_blank: 'Seleccione una Forma de Pago'}, html_options = {class: 'form-control'})
                %div#rowNumero{style: (f.object.tipo_pago == 'Cheque') ? '' : 'display:none'}
                  .form-group
                    = f.label :nro_cheque_confirmacion, "Nro Cheque:", class: 'col-sm-2 control-label'
                    .col-sm-10
                      = f.text_field :nro_cheque_confirmacion, class: "form-control", id: 'input_cheque_nro_confirmacion'
                %div#rowBanco{style: (f.object.tipo_pago == 'Cheque') ? '' : 'display:none'}
                  .form-group
                    = f.label :banco_emisor, "Cheque del Banco:", class: 'col-sm-2 control-label'
                    .col-sm-10
                      = f.text_field :banco_emisor, class: "form-control"
                .form-group
                  = f.label :cuenta_bancaria, "Nro. Cuenta a Depositar: ", class: 'col-sm-2 control-label'
                  .col-sm-10
                    .group-show
                      = f.select(:cuenta_bancarium_id,{},{include_blank: 'Seleccione la cuenta bancaria'},html_options = {class: "form-control"})  do
                        - CuentaBancarium.all.each do |c|
                          = content_tag(:option, c.banco.nombre+'  '+c.nro_cta, value: c.id)
                        - {class: "form-control"}
                .form-group
                  .col-sm-3.col-sm-offset-9
                    = f.submit "Guardar", id: "btn_guardar", class: "btn btn-warning btn-block", disabled: true

app/views/pago_alquilers/show.html.haml
%br
%br
.panel.panel-success
  .panel-heading
    %h3
      Recibo de Pago N°:
      = @pago_alquiler.nro_recibo
  .panel-body
    %p.text-success
    = render 'datos_recibo'